apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    component: web
spec:
  containers:
    - ports:
        - containerPort: 3000
      name: client
      image: worasit501/multi-client
      imagePullPolicy: IfNotPresent
