apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  selector:
    matchLabels:
      component: web
  replicas: 5
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: worasit501/multi-client
          ports:
            - containerPort: 3000

